version: '3'
 
services:
 
  db:
    image: mysql:5.7.22
    container_name: db
    ports:
      - '3306:3306'
    networks:
      - app-network
    environment:
      MYSQL_DATABASE:  ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}`
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./sql:/usr/local/etc/mysql

  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php 
    container_name: app 
    volumes:
       - ./code:/data/application.local

    networks:
      - app-network

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    volumes:
     - ./code:/data/application.local
     - ./php.ini:/usr/local/etc/php/conf.d/php.ini

   # проброс портов
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
